//! Local device state: a private key generated by the installed WireGuard
//! tools and a small JSON record of the enrollment. Files are created with
//! mode 0600 inside a 0700 directory and are never overwritten by accident.
//!
//! A record is *pending* while `member_id` is empty: the key exists locally
//! and may or may not have been recorded by the control plane. Pending records
//! are loadable so a retried `join` can reconcile and finish them, and they
//! are only ever deleted by a definitive refusal or an explicit request.
use super::model::{validate_name, validate_uuid, PublicKey};
use anyhow::{bail, ensure, Context, Result};
use serde::{Deserialize, Serialize};
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::time::Duration;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemberState {
    pub network_id: String,
    pub network_name: String,
    /// Empty until the control plane confirmed the enrollment.
    pub member_id: String,
    pub member_name: String,
    pub role: String,
    pub public_key: String,
    /// False when the device enrolled with a key generated elsewhere.
    pub has_private_key: bool,
}

impl MemberState {
    /// True while the enrollment was never confirmed by the control plane.
    pub fn is_pending(&self) -> bool {
        self.member_id.is_empty()
    }
}

/// Commands that need a member id refuse a pending record with the two ways out.
pub fn require_committed(state: &MemberState) -> Result<()> {
    ensure!(
        !state.is_pending(),
        "the enrollment of {member} in {network} is pending (the control plane never confirmed it); rerun `pike network join {network} --as {member}` to finish it, or `pike network leave {network} --as {member} --forget-local` to discard the local key",
        member = state.member_name,
        network = state.network_name
    );
    Ok(())
}

pub struct MemberPaths {
    pub dir: PathBuf,
    pub state: PathBuf,
    pub key: PathBuf,
}

/// `<config dir>/networks/<network id>/<member>.{json,key}`.
pub fn member_paths(config_path: &Path, network_id: &str, member: &str) -> Result<MemberPaths> {
    let network_id = validate_uuid(network_id)?;
    let member = validate_name(member)?;
    let base = config_path
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .map_or_else(|| PathBuf::from("."), Path::to_path_buf)
        .join("networks");
    let dir = base.join(network_id);
    Ok(MemberPaths {
        state: dir.join(format!("{member}.json")),
        key: dir.join(format!("{member}.key")),
        dir,
    })
}

#[cfg(unix)]
fn private_dir(path: &Path) -> Result<()> {
    use std::os::unix::fs::{DirBuilderExt, PermissionsExt};
    if !path.exists() {
        fs::DirBuilder::new()
            .recursive(true)
            .mode(0o700)
            .create(path)
            .with_context(|| format!("failed to create {}", path.display()))?;
    }
    fs::set_permissions(path, fs::Permissions::from_mode(0o700))?;
    Ok(())
}

#[cfg(not(unix))]
fn private_dir(path: &Path) -> Result<()> {
    fs::create_dir_all(path).with_context(|| format!("failed to create {}", path.display()))
}

fn create_private(path: &Path, content: &str) -> Result<()> {
    let mut options = OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let mut file = options.open(path).with_context(|| {
        format!(
            "refusing to overwrite {}; run `pike network leave` first",
            path.display()
        )
    })?;
    file.write_all(content.as_bytes())?;
    Ok(())
}

fn remove_if_present(path: &Path) -> Result<()> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error).with_context(|| format!("failed to remove {}", path.display())),
    }
}

/// `<member>.json.tmp`: the only temporary file this module ever creates or
/// removes. It never holds private key material.
fn temp_state_path(paths: &MemberPaths) -> PathBuf {
    paths.state.with_extension("json.tmp")
}

pub fn save_new(paths: &MemberPaths, state: &MemberState, private_key: Option<&str>) -> Result<()> {
    private_dir(&paths.dir)?;
    if paths.state.exists() || paths.key.exists() {
        bail!(
            "{} is already enrolled locally ({}); run `pike network leave` first",
            state.member_name,
            paths.dir.display()
        );
    }
    // A temporary record left by an interrupted rewrite carries no key; clear it.
    remove_if_present(&temp_state_path(paths))?;
    create_private(&paths.state, &serde_json::to_string_pretty(state)?)?;
    if let Some(key) = private_key {
        if let Err(error) = create_private(&paths.key, &format!("{key}\n")) {
            let _ = fs::remove_file(&paths.state);
            return Err(error);
        }
    }
    Ok(())
}

/// Replace the enrollment record (for example once the server assigned the
/// member id) atomically: the new record is written to a private temporary
/// file in the same directory and renamed over the old one, so a crash at
/// any point leaves either the previous or the new record, never neither.
/// The key file is untouched.
pub fn rewrite_state(paths: &MemberPaths, state: &MemberState) -> Result<()> {
    let temp = temp_state_path(paths);
    remove_if_present(&temp)?;
    create_private(&temp, &serde_json::to_string_pretty(state)?)?;
    if let Err(error) = fs::rename(&temp, &paths.state) {
        let _ = fs::remove_file(&temp);
        return Err(error).with_context(|| format!("failed to replace {}", paths.state.display()));
    }
    Ok(())
}

/// The local record, pending or committed, or None when this member has none.
pub fn load_existing(paths: &MemberPaths) -> Result<Option<MemberState>> {
    if !paths.state.exists() {
        ensure!(
            !paths.key.exists(),
            "{} holds a private key without an enrollment record; move it away by hand before enrolling this member again",
            paths.key.display()
        );
        return Ok(None);
    }
    load(paths).map(Some)
}

/// Locate a local enrollment (pending or committed) by network name and
/// member name without the control plane, so gateways need only
/// `networks:run` and `leave` still works after the network was deleted.
pub fn find_state(
    config_path: &Path,
    network_name: &str,
    member: &str,
) -> Result<(MemberPaths, MemberState)> {
    validate_name(network_name)?;
    validate_name(member)?;
    let base = member_paths(config_path, "00000000-0000-0000-0000-000000000000", member)?
        .dir
        .parent()
        .map(Path::to_path_buf)
        .context("invalid state directory")?;
    let mut found = None;
    if let Ok(entries) = fs::read_dir(&base) {
        for entry in entries.flatten() {
            let Some(network_id) = entry.file_name().to_str().map(str::to_owned) else {
                continue;
            };
            let Ok(paths) = member_paths(config_path, &network_id, member) else {
                continue;
            };
            let Ok(state) = load(&paths) else { continue };
            if state.network_name == network_name && state.member_name == member {
                ensure!(found.is_none(), "{member} is enrolled in more than one network named {network_name}; remove the stale record");
                found = Some((paths, state));
            }
        }
    }
    found.with_context(|| {
        format!(
            "{member} is not enrolled in {network_name} on this device (no record under {})",
            base.display()
        )
    })
}

pub fn load(paths: &MemberPaths) -> Result<MemberState> {
    let text = fs::read_to_string(&paths.state)
        .with_context(|| format!("not enrolled locally ({} missing)", paths.state.display()))?;
    let state: MemberState = serde_json::from_str(&text).context("corrupt enrollment record")?;
    validate_uuid(&state.network_id)?;
    if !state.is_pending() {
        validate_uuid(&state.member_id)?;
    }
    validate_name(&state.member_name)?;
    PublicKey::parse(&state.public_key)?;
    Ok(state)
}

/// The private key is read only by gateway and config commands and never logged.
pub fn load_private_key(paths: &MemberPaths) -> Result<String> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mode = fs::metadata(&paths.key)
            .with_context(|| format!("private key missing at {}", paths.key.display()))?
            .permissions()
            .mode()
            & 0o777;
        ensure!(
            mode & 0o077 == 0,
            "{} must not be group or world accessible",
            paths.key.display()
        );
    }
    let key = fs::read_to_string(&paths.key)
        .with_context(|| format!("private key missing at {}", paths.key.display()))?;
    let key = key.trim();
    PublicKey::parse(key).context("private key file is not a WireGuard key")?;
    Ok(key.to_owned())
}

/// Remove this member's key, record and temporary record only; the directory
/// goes only if nothing else is in it.
pub fn remove(paths: &MemberPaths) -> Result<()> {
    for path in [&paths.key, &paths.state, &temp_state_path(paths)] {
        remove_if_present(path)?;
    }
    let _ = fs::remove_dir(&paths.dir);
    Ok(())
}

async fn wg(args: &[&str], stdin: Option<&str>) -> Result<String> {
    let mut command = tokio::process::Command::new("wg");
    command
        .args(args)
        .stdin(if stdin.is_some() {
            Stdio::piped()
        } else {
            Stdio::null()
        })
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .kill_on_drop(true);
    // Like every gateway child, wg dies with the process that spawned it.
    super::gateway::die_with_parent(&mut command);
    let mut child = command
        .spawn()
        .context("wireguard-tools (`wg`) is required; install it or enroll with --public-key")?;
    if let Some(input) = stdin {
        if let Some(mut pipe) = child.stdin.take() {
            use tokio::io::AsyncWriteExt;
            pipe.write_all(input.as_bytes()).await?;
            pipe.shutdown().await?;
        }
    }
    let output = tokio::time::timeout(Duration::from_secs(10), child.wait_with_output())
        .await
        .context("wg timed out")??;
    ensure!(
        output.status.success(),
        "wg {} failed ({})",
        args[0],
        output.status
    );
    Ok(String::from_utf8(output.stdout)?.trim().to_owned())
}

/// Returns (private, public). Generated by `wg genkey` / `wg pubkey`.
pub async fn generate_keypair() -> Result<(String, PublicKey)> {
    let private = wg(&["genkey"], None).await?;
    PublicKey::parse(&private).context("wg genkey produced an unexpected key")?;
    let public = PublicKey::parse(&wg(&["pubkey"], Some(&format!("{private}\n"))).await?)?;
    Ok((private, public))
}

/// Derive the public key of a stored private key to prove local ownership.
pub async fn public_key_of(private: &str) -> Result<PublicKey> {
    PublicKey::parse(&wg(&["pubkey"], Some(&format!("{private}\n"))).await?)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn state() -> MemberState {
        MemberState {
            network_id: "0f8fad5b-d9cb-469f-a165-70867728950e".into(),
            network_name: "lab".into(),
            member_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7".into(),
            member_name: "c1".into(),
            role: "client".into(),
            public_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=".into(),
            has_private_key: true,
        }
    }

    #[test]
    fn paths_are_confined_and_validated() {
        let config = Path::new("/tmp/pike-test/config.toml");
        let paths = member_paths(config, "0f8fad5b-d9cb-469f-a165-70867728950e", "c1").unwrap();
        assert_eq!(
            paths.dir,
            Path::new("/tmp/pike-test/networks/0f8fad5b-d9cb-469f-a165-70867728950e")
        );
        assert_eq!(paths.key.file_name().unwrap(), "c1.key");
        assert!(member_paths(config, "../../etc", "c1").is_err());
        assert!(member_paths(config, "0f8fad5b-d9cb-469f-a165-70867728950e", "../c1").is_err());
    }

    #[test]
    fn files_are_private_and_never_overwritten() {
        let temp = tempfile::TempDir::new().unwrap();
        let config = temp.path().join("config.toml");
        let paths = member_paths(&config, "0f8fad5b-d9cb-469f-a165-70867728950e", "c1").unwrap();
        save_new(
            &paths,
            &state(),
            Some("cPrivateKeyIsNeverLoggedAAAAAAAAAAAAAAAAAAE="),
        )
        .unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(&paths.dir).unwrap().permissions().mode() & 0o777,
                0o700
            );
            assert_eq!(
                fs::metadata(&paths.key).unwrap().permissions().mode() & 0o777,
                0o600
            );
            assert_eq!(
                fs::metadata(&paths.state).unwrap().permissions().mode() & 0o777,
                0o600
            );
        }
        assert_eq!(load(&paths).unwrap().member_id, state().member_id);
        assert_eq!(
            load_private_key(&paths).unwrap(),
            "cPrivateKeyIsNeverLoggedAAAAAAAAAAAAAAAAAAE="
        );
        let (found_paths, found) = find_state(&config, "lab", "c1").unwrap();
        assert_eq!(found_paths.key, paths.key);
        assert_eq!(found.network_id, state().network_id);
        assert!(find_state(&config, "other", "c1")
            .err()
            .expect("missing enrollment must fail")
            .to_string()
            .contains("not enrolled"));
        assert!(find_state(&config, "lab", "c2").is_err());
        let again = save_new(&paths, &state(), Some("other"))
            .unwrap_err()
            .to_string();
        assert!(again.contains("already enrolled locally"), "{again}");
        remove(&paths).unwrap();
        assert!(!paths.state.exists() && !paths.key.exists());
        remove(&paths).unwrap();
        let mut no_key = state();
        no_key.has_private_key = false;
        save_new(&paths, &no_key, None).unwrap();
        assert!(!paths.key.exists());
        assert!(load_private_key(&paths).is_err());
    }

    #[test]
    fn a_pending_record_is_loadable_recoverable_and_explicitly_not_committed() {
        let temp = tempfile::TempDir::new().unwrap();
        let config = temp.path().join("config.toml");
        let paths = member_paths(&config, "0f8fad5b-d9cb-469f-a165-70867728950e", "c1").unwrap();
        let pending = MemberState {
            member_id: String::new(),
            ..state()
        };
        assert!(load_existing(&paths).unwrap().is_none());
        save_new(
            &paths,
            &pending,
            Some("cPrivateKeyIsNeverLoggedAAAAAAAAAAAAAAAAAAE="),
        )
        .unwrap();
        // Pending records load, are found by name, and say so.
        let loaded = load(&paths).unwrap();
        assert!(loaded.is_pending());
        assert!(load_existing(&paths)
            .unwrap()
            .is_some_and(|s| s.is_pending()));
        let (_, found) = find_state(&config, "lab", "c1").unwrap();
        assert!(found.is_pending());
        let refused = require_committed(&found)
            .err()
            .expect("a pending record is not a committed enrollment")
            .to_string();
        assert!(
            refused.contains("pending")
                && refused.contains("--forget-local")
                && refused.contains("join lab --as c1"),
            "{refused}"
        );
        // The key survives while pending and is unchanged by the completion.
        let key_before = fs::read(&paths.key).unwrap();
        rewrite_state(&paths, &state()).unwrap();
        let committed = load(&paths).unwrap();
        assert!(!committed.is_pending());
        assert_eq!(committed.member_id, state().member_id);
        require_committed(&committed).unwrap();
        assert_eq!(fs::read(&paths.key).unwrap(), key_before);
        // A record whose member id is neither empty nor a UUID is corrupt.
        fs::write(
            &paths.state,
            serde_json::to_string(&MemberState {
                member_id: "nope".into(),
                ..state()
            })
            .unwrap(),
        )
        .unwrap();
        assert!(load(&paths).is_err());
        // A key file without a record is never silently reused or deleted.
        fs::remove_file(&paths.state).unwrap();
        assert!(load_existing(&paths)
            .err()
            .expect("orphan key must be reported")
            .to_string()
            .contains("without an enrollment record"));
    }

    #[test]
    fn rewrite_is_atomic_private_and_cleans_only_its_own_temporary_file() {
        let temp = tempfile::TempDir::new().unwrap();
        let config = temp.path().join("config.toml");
        let paths = member_paths(&config, "0f8fad5b-d9cb-469f-a165-70867728950e", "c1").unwrap();
        let pending = MemberState {
            member_id: String::new(),
            ..state()
        };
        save_new(
            &paths,
            &pending,
            Some("cPrivateKeyIsNeverLoggedAAAAAAAAAAAAAAAAAAE="),
        )
        .unwrap();
        let temp_record = temp_state_path(&paths);
        assert_eq!(temp_record.file_name().unwrap(), "c1.json.tmp");
        // A stale temporary record from an interrupted earlier rewrite is replaced, not appended to.
        fs::write(&temp_record, "stale").unwrap();
        let unrelated = paths.dir.join("c1.json.bak");
        fs::write(&unrelated, "not ours").unwrap();
        rewrite_state(&paths, &state()).unwrap();
        assert!(
            !temp_record.exists(),
            "the temporary record is renamed over the old one"
        );
        assert!(
            unrelated.exists(),
            "only the exact temporary path is ever touched"
        );
        assert_eq!(load(&paths).unwrap().member_id, state().member_id);
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(&paths.state).unwrap().permissions().mode() & 0o777,
                0o600
            );
        }
        // The record is never removed before the replacement exists: rewriting
        // into a directory that vanished fails and leaves nothing half-written.
        let gone = member_paths(&config, "11111111-2222-3333-4444-555555555555", "c1").unwrap();
        assert!(rewrite_state(&gone, &state()).is_err());
        assert!(!gone.state.exists() && !temp_state_path(&gone).exists());
        // remove() takes the temporary file too, and only that.
        fs::write(&temp_record, "stale").unwrap();
        remove(&paths).unwrap();
        assert!(!paths.state.exists() && !paths.key.exists() && !temp_record.exists());
        assert!(unrelated.exists());
        fs::remove_file(&unrelated).unwrap();
        // A fresh save clears a stale temporary record as well.
        fs::create_dir_all(&paths.dir).unwrap();
        fs::write(&temp_record, "stale").unwrap();
        save_new(&paths, &pending, None).unwrap();
        assert!(!temp_record.exists());
    }
}
